[package]
name = "pitchlake-pricing"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
polars = { version = "0.41.3", features = ["lazy", "dynamic_group_by", "rolling_window"] }
polars-core = "0.41.3"
polars-io = "0.41.3"
